spring:
  datasource:
#    url: jdbc:postgresql://u91845748498.postgres.database.azure.com:5432/u666e9de826c?user=ub0a7e1df0a6%40u91845748498&password=VjtwJRFx21vMd53CLe6AeDdmadXCfARs3BxtVFG5NuBxJ8UNMOt%2FJg%3D%3D&ssl=false #PROD
#    url: jdbc:postgresql://localhost:5433/u666e9de826c?user=ub0a7e1df0a6%40u91845748498&password=VjtwJRFx21vMd53CLe6AeDdmadXCfARs3BxtVFG5NuBxJ8UNMOt%2FJg%3D%3D&ssl=false #PROD tunnel
#    url: jdbc:postgresql://u366dc92d9a3.postgres.database.azure.com:5432/u30e63000ce8?user=uee3fcf59763@u366dc92d9a3&password=rhQCAg6YXNl3VudH7m8g/womCGsUTcl2JJmyhobIoAfbAEMIDyPthg==&ssl=false #BUGBOUNTY
    url: jdbc:postgresql://localhost:5434/1logistics-db #local
#    url: jdbc:postgresql://u23b7ade3b17.postgres.database.azure.com:5432/ub6ca547d763?user=u76232b37339%40u23b7ade3b17&password=5ppzrJk1kABXs13yik9SbqQe%2BPyq6nuHrplt5Gtr6%2BvODmB6DQLeBQ%3D%3D&ssl=false #DEV
#    url: jdbc:postgresql://localhost:5434/ub6ca547d763?user=u76232b37339%40u23b7ade3b17&password=5ppzrJk1kABXs13yik9SbqQe%2BPyq6nuHrplt5Gtr6%2BvODmB6DQLeBQ%3D%3D&ssl=false #DEV tunnel

logging:
  level:
#    org.springframework.security: DEBUG
    org.springframework.security: INFO

jwk:
  endpoint: http://localhost:3000/keys
  client-id: 0a798b67-8c79-4757-b24c-c307aca4d071

BACKEND_CLIENT_SECRET: ZfBm1=K1TAWO3I8gjtQqrhT.RbJz.Po/ # DEV: this is provided in the intellij config
#BACKEND_CLIENT_SECRET: 1B85aSZ9_4J9J~X3Upm.QqS1x6yu~rzjeO #QUALIF
#BACKEND_CLIENT_SECRET: 94U55~b6R4J-5.N.lnAs_2GJIynX0vOaF9 # PROD: this is provided in the intellij config
POINTER_PASSWORD: Proto2019
USER_GUIDE_FILENAME: 1Logistics_userguide.pdf
ORIGIN: http://localhost:3000
#AZURE_CLIENT_ID: da8a0a65-c964-4c1c-b40d-977c6897d5ae #QUALIF
AZURE_CLIENT_ID: dc31d69b-c550-4649-9a40-91560ce133ef #LOCAL
AZURE_TENANT_ID: 48dfefd8-e151-444d-973c-ef22589f5aa5

#AZURE_CLIENT_ID: 53a0d03a-8a75-4660-a95e-d354ade76610 #PROD
#AZURE_TENANT_ID: 737c6905-f186-4bcf-afb3-43e349ee23a3 #PROD
INFORMATION_NOTICE_FILENAME: information_notice.pdf
# every 5 secs
CRON_JOB: 0/5 * * ? * *
CRON_JOB_ALARM: 59 59 23 31 DEC *
# ever minute
#CRON_JOB: 0 */1 * ? * *
# once a year
#CRON_JOB: "59 59 23 31 DEC *"
NANONET_MODEL_ID: a396226e-1b2f-45a9-929b-611bcc591119
NANONET_API_KEY: XwB0D5HCemX5hExmrUMWGmKNtbOtmyi9
OPENALPR_SECRET_KEY: sk_25d948761f64e3f998232e4a
OPENALPR_API_URL: https://api.openalpr.com/v3/recognize_bytes?recognize_vehicle=1&country=eu&secret_key=
LIQUIBASE_ENABLED: true
INVITATION_MESSAGE: "Join Protostellar"
USER_ALREADY_IN_GROUP: "User already in group"
SEND_INVITATION_BY_MAIL: true
MS_SCOPE: https://graph.microsoft.com/.default
USER_GROUP_ID: "0c336631-008f-484e-9c5d-388b6db213a5" #QUALIF
#USER_GROUP_ID: "6481081a-2400-4bda-8b87-191a7093bf14" # PROD
URL_FRONT: http://localhost:3000
